### ISSUE TITLE
[Low Priority] Clean code

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/chamber-lang#17]
## Why

It's time to clean code because the compiler design was almost done.

## How

* use typescript
* don't use parcel(@tkmct any recommendation?)
* separate compiler and online web site?
* auto deployment
* prettier

**Comment by tkmct** [comment]
If it's static website, just using Gatsby or next.js is okay choice.

**Comment by syuhei176** [comment]
> separate compiler and online web site?

I'll separate the compiler because it will become bigger component. It'll include parser, code generator and some utilities to decompile property.

**Comment by syuhei176** [comment]
separeted
